### ISSUE TITLE
Ability to create and store metrics for Wind Tunnel scenarios

### ISSUE THREAD

**Issue by maackle** [holochain/wind-tunnel#43]
- Select a storage mechanism. InfluxDB? Filesystem?
- Provide an API to be used in writing scenarios
- This could be a simple key-value store

This is related to https://github.com/holochain/wind-tunnel/issues/6, which defines how we actually extract info from the metrics store

**Comment by abe-njama** [comment]
We currently have a solution for this, which is InfluxDB
