### ISSUE TITLE
Wind Tunnel scenario execution

### ISSUE THREAD

**Issue by ThetaSinner** [holochain/wind-tunnel#5]
Wind Tunnel is most useful when scenarios are run regularly in the same environment.

 ~~There is already a Nomad cluster which has been set up for testing and can be used for this purpose.~~
The plan had been to run Wind Tunnel scenarios on a Nomad cluster, but that cluster didn't get delivered. Instead we have been allocated a VM that we can use as a github runner and run tests directly on. Some of those tests will just run against Holochain on the runner itself, and others will run against Holoports. The machine is already connected to the Holo network, so it will be able to access the machines in the `targets.yaml` [list](https://github.com/holochain/wind-tunnel/blob/main/targets.yaml).

Completion of this issue requires:
- [x] There is a machine (the allocated VM or otherwise), that can be used for running tests.
- [x] There is a github workflow that can be triggered manually to run the performance tests.
- [x] When tests are run from the test runner, metrics are collected by Telegraf and published to our Influx DB instance.
- [ ] Target nodes can be cleaned after a run. E.g. so that Holochain is stopped and its data cleared between runs. This is partially taken care of by TryCP scenarios but we might want to force the cleanup between scenarios?
- [x] (Nice to have) There is a mechanism for retrieving logs from the test runner. The TryCP tests can already collect logs from remote nodes to the runner, and for local tests we can direct Holochain output to a file. Then we need some way of gathering those logs and somewhere to put them.

**Comment by ThetaSinner** [comment]
Best estimate for this issue is 2 weeks.

**Comment by neonphog** [comment]
We might need to spike/design more to understand how to implement these requirements: there is currently some flux with tfgrid development, etc.

**Comment by steveej** [comment]
we should be able to develop scenarios without requiring access to a big real-world execution cluster.
